### ISSUE TITLE
插件的指令不能用

### ISSUE THREAD

**Issue by Akira991** [Saukiya/SX-Level#2]
[19:27:07 ERROR]: Error occurred while enabling SX-Level v1.2.1 (Is it up to date?)
 java.lang.NoClassDefFoundError: github/saukiya/sxlevel/util/Placeholders
        at github.saukiya.sxlevel.SXLevel.onEnable(SXLevel.java:72) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
        at com.mohistmc.util.pluginmanager.PluginManagers.reloadPluginCommand(PluginManagers.java:114) [PluginManagers.class:?]
        at com.mohistmc.command.PluginCommand.execute(PluginCommand.java:52) [PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) [SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) [CraftServer.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:738) [CraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:510) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.ClassNotFoundException: Failed to remap class github.saukiya.sxlevel.util.Placeholders
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:209) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:123) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        ... 14 more
Caused by: java.lang.NoClassDefFoundError: me/clip/placeholderapi/external/EZPlaceholderHook
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_301]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:185) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:123) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.external.EZPlaceholderHook
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:126) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_301]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:185) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:123) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301]
        ... 14 more

**Comment by Saukiya** [comment]
SX-Level已经与最新版Placeholder不兼容，而且该版本SX-Level存在回档问题
